# Generated by Django 4.2.7 on 2025-08-16 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('github_url', models.URLField(blank=True, verbose_name='URL de GitHub')),
                ('live_url', models.URLField(blank=True, verbose_name='URL del sitio en vivo')),
                ('technologies', models.CharField(help_text='Separar con comas', max_length=500, verbose_name='Tecnologías')),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
