# Generated by Django 4.2.7 on 2025-11-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (ImgBB, GitHub, etc)', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
