# Generated by Django 4.2.7 on 2025-08-17 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(help_text='Resumen breve del servicio', max_length=300, verbose_name='Descripción corta')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen')),
                ('price_type', models.CharField(choices=[('fixed', 'Precio fijo'), ('hourly', 'Por hora'), ('project', 'Por proyecto'), ('quote', 'Cotización')], default='quote', max_length=20, verbose_name='Tipo de precio')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio desde')),
                ('price_currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('duration', models.CharField(choices=[('1-2_weeks', '1-2 semanas'), ('3-4_weeks', '3-4 semanas'), ('1-2_months', '1-2 meses'), ('3-6_months', '3-6 meses'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Duración')),
                ('custom_duration', models.CharField(blank=True, max_length=100, verbose_name='Duración personalizada')),
                ('features', models.JSONField(default=list, help_text='Lista de características del servicio', verbose_name='Características')),
                ('technologies', models.JSONField(default=list, help_text='Tecnologías utilizadas en este servicio', verbose_name='Tecnologías')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('show_price', models.BooleanField(default=True, verbose_name='Mostrar precio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icono')),
                ('color', models.CharField(default='#1d6ff2', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icono')),
                ('is_included', models.BooleanField(default=True, verbose_name='Incluido')),
                ('additional_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo adicional')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_features', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Característica de Servicio',
                'verbose_name_plural': 'Características de Servicios',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Categoría'),
        ),
    ]
