# Generated by Django 4.2.7 on 2025-11-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_price_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa', max_length=500, verbose_name='URL de Imagen'),
        ),
    ]
