# Generated by Django 4.2.7 on 2025-08-16 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en hexadecimal', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen destacada')),
                ('tags', models.CharField(blank=True, help_text='Separar con comas', max_length=200, verbose_name='Etiquetas')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción')),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Tiempo de lectura en minutos', verbose_name='Tiempo de lectura')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Post del Blog',
                'verbose_name_plural': 'Posts del Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
