# Generated by Django 4.2.7 on 2025-08-16 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS o emoji', max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Habilidad',
                'verbose_name_plural': 'Categorías de Habilidades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('level', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Experto', 'Experto')], max_length=20, verbose_name='Nivel')),
                ('icon', models.CharField(blank=True, help_text='Emoji o clase CSS', max_length=50, verbose_name='Icono')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
