# Generated by Django 4.2.7 on 2025-08-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_change_image_url_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#74b9ff', help_text='Color hexadecimal para el fondo del ícono (ej: #74b9ff)', max_length=7, verbose_name='Color'),
        ),
    ]
