# Generated by Django 4.2.7 on 2025-08-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='gradient_type',
            field=models.CharField(choices=[('linear-left', 'Degradado Horizontal (Izq → Der)'), ('linear-right', 'Degradado Horizontal (Der → Izq)'), ('linear-top', 'Degradado Vertical (Arriba → Abajo)'), ('linear-bottom', 'Degradado Vertical (Abajo → Arriba)'), ('linear-diagonal-1', 'Degradado Diagonal (↘)'), ('linear-diagonal-2', 'Degradado Diagonal (↙)'), ('linear-diagonal-3', 'Degradado Diagonal (↗)'), ('linear-diagonal-4', 'Degradado Diagonal (↖)'), ('radial-center', 'Degradado Radial (Centro)'), ('radial-corner', 'Degradado Radial (Esquina)'), ('conic', 'Degradado Cónico'), ('solid', 'Color Sólido')], default='linear-diagonal-1', max_length=20, verbose_name='Tipo de Degradado'),
        ),
    ]
