# Generated by Django 4.2.7 on 2025-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_gradient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='gradient_css',
            field=models.TextField(blank=True, help_text='Ejemplo: linear-gradient(135deg, #ff6b6b 0%, #4ecdc4 100%). Si está vacío, se usará el color y tipo seleccionados arriba.', verbose_name='CSS del Degradado Personalizado'),
        ),
    ]
