# Generated by Django 4.2.7 on 2025-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_gradient_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at', 'category', 'order', 'name'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='skill',
            name='background_type',
            field=models.CharField(choices=[('transparent', 'Sin Fondo (Transparente)'), ('solid', 'Color Sólido'), ('gradient', 'Degradado')], default='gradient', max_length=20, verbose_name='Tipo de Fondo'),
        ),
    ]
