# Generated by Django 4.2.7 on 2025-08-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_skill_options_skill_background_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-created_at', 'category', 'name'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_icon',
            field=models.CharField(blank=True, help_text='Emoji o clase CSS para tecnología relacionada (ej: Spring para Java)', max_length=50, verbose_name='Sub-Icono'),
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/sub/', verbose_name='Sub-Imagen'),
        ),
    ]
