# Generated by Django 4.2.7 on 2025-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_skill_options_skill_sub_icon_skill_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_dark',
            field=models.ImageField(blank=True, help_text='Opcional. Si no se proporciona, se usará la imagen normal', null=True, upload_to='skills/', verbose_name='Imagen (Modo Oscuro)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_image_dark',
            field=models.ImageField(blank=True, help_text='Opcional. Si no se proporciona, se usará la sub-imagen normal', null=True, upload_to='skills/sub/', verbose_name='Sub-Imagen (Modo Oscuro)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Imagen (Modo Claro)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/sub/', verbose_name='Sub-Imagen (Modo Claro)'),
        ),
    ]
