# Generated by Django 4.2.7 on 2025-08-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_skill_image_dark_skill_sub_image_dark_and_more'),
    ]

    operations = [
    ]
