# Generated by Django 4.2.7 on 2025-08-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_auto_20250817_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sub_image_dark',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/sub/', verbose_name='Sub-Imagen'),
        ),
    ]
