# Generated by Django 4.2.7 on 2025-11-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_remove_skill_image_dark_remove_skill_sub_image_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (CDN, etc)', max_length=500, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_image_url',
            field=models.URLField(blank=True, help_text='URL de sub-imagen externa', max_length=500, verbose_name='URL de Sub-Imagen'),
        ),
    ]
